### ISSUE TITLE
Triodos Bank UK

### ISSUE THREAD

**Issue by ph00lt0** [akc3n/banking#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Triodos Bank UK

### Link to app

https://play.google.com/store/apps/details?id=com.triodos.bankinguk

### App version

2.12.1

### Country of the app

United Kingdom

### Build Number

TP1A.220624.014.2022082400

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [X] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All functions work as expected.

**Comment by akc3n** [comment]
Thanks @ph00lt0

**Comment by treequell** [comment]
A recent update to this app seems to have created a memory corruption bug uncovered by GrapheneOS.

When I open the app (version 3.52.1) with exploit protection compatibility mode disabled, the app crashes upon launch. If I enable the exploit protection compatibility mode the app functions as expected. Prior to this update, the app functioned as expected even with the exploit protection compatibility mode disabled.

Tested on:
- Pixel 7 running GrapheneOS TQ1A.230205.002.2023030400
- App installed in owner profile
- Google Play Store and sandboxed Google Play Services all with network permission
- Secure app spawning enabled
- Native code debugging disabled

**Comment by floatingatoms** [comment]
Hello this app now requires native code debugging to be enabled, version 4.7.7

**Comment by floatingatoms** [comment]
This app, like the NL version, does not work anymore. When opening the app it now runs a check and then decides to kill itself after sending the user to a help page on their website. I imagine the backend of their app is shared between countries so hoping if one of them can be convinced to fix it, it'll also come to the other countries

**Comment by axelsimon** [comment]
@ph00lt0  @akc3n Can we please reopen this issue, as it is an ongoing issue that hasn't been resolved one way or another.

**Comment by ph00lt0** [comment]
First of all I don't have this issue, it is probably your settings, secondly this is not my repo and I cannot reopen it.

**Comment by floatingatoms** [comment]
> [@ph00lt0](https://github.com/ph00lt0) [@akc3n](https://github.com/akc3n) Can we please reopen this issue, as it is an ongoing issue that hasn't been resolved one way or another.

Just also noting that the app has been working fine for me ever since they addressed it for the NL version, see #133 for that.

**Comment by axelsimon** [comment]
@ph00lt0 I'm glad you don't have this issue. As i'm sure you have guessed, i do, which is why i called it "ongoing". I am not aware of any settings i can change on CalyxOS to fix this. I would happily try to change settings to get this to work, but MicroG appears to be functional and no changes to settings there that i have tried make any difference.

I spoke to Triodos UK yesterday who were unable to provide any meaningful help or progress. They pointed out that they were entirely separate to Triodos NL. That may not be correct regarding the app's code, but that is what i was told.
I was essentially told the issue is with me "not using Android", which i corrected to point out that:
1. I am using Android, as CalyxOS is a version of Android and a safer one at that than the default one that ships with most devices and
2. The issue inherently stems from changes they have made in the app, as it used to work fine before said changes.

It appears my best option right now is to move to GrapheneOS, which i'm not really excited about.

edit: i have just seen in the repo's README that this repo is to "Report and track international banking app compatibility with GrapheneOS", sorry, i arrived here through direct links (to #133 ) where mentions of CalyxOS made me believe this repo was for all security-aware deGoogled Android distros. Sorry for the noise then!

**Comment by ph00lt0** [comment]
@axelsimon so your comment is completely in the wrong place. This repo is about GrapheneOS compatibility. Not about OSes that take other approaches that result in issues like yours.

**Comment by Maggus101** [comment]
Just went through applying
Play services and play store required for identity verification. Used secondary profile.
Exploit protection required turning off for location verification to work.
