### ISSUE TITLE
N26 The Mobile Bank - Germany

### ISSUE THREAD

**Issue by togethereveryday** [akc3n/banking#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

N26 - The Mobile Bank

### Link to app

https://play.google.com/store/apps/details?id=de.number26.android&hl=en_US&gl=US

### App version

3.73

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works. 

- Transactions
- Push notifications
- Push verification
- Biometric verification

### Are there any extra notes you think users should know about?

I have not tested Google Pay functionality.

**Comment by arn0nym0us** [comment]
When pairing your phone as main device,
the link sent in the confirmation Mail won't work by default.
To make it work you need to go to the n26 "App Info" -> "open by default" 
and add n26 as default there.

**Comment by akc3n** [comment]
@arn0nym0us thanks for the additional information

**Comment by AltGr** [comment]
Had no problem with the confirmation mail, but the heavyweight identification (take a selfie + video, etc.) would fail at the GPS stage (yes, they even try to validate your position 🙄 ) ; until I installed the sandboxed GApps (without network permission IIRC), then the device registration worked (and I can remove GApps again)

**Comment by Nick1296** [comment]
I just have a tiny update for the latest version of grtapheneOS at the time of writing.

Since N26 want you to verify your location, make sure that you have the "Reroute location requests to the OS" toggled OFF, while associating your device.

You can find the setting in `settings -> apps -> sandboxed google play`
Just to be sure I also enabled google location accuracy and gave play services access to location and nearby devices.

**Comment by stephane-21** [comment]
Since recently, N26 app is using the Google Play Integrity API, and we have to "**Allow** usage attempts" in the app settings.

Beside that, all the other settings can be set on the "safe" side :
- Exploit protection compatibility mode = OFF
- Hardened memory allocator = Enabled
- Memory tagging = Enabled
- Native code debugging = Blocked
- Webview JIT = Disabled
- Dynamic code loading via memory = Restricted
- Dynamic code loading via storage = Restricted

**Comment by Navia25** [comment]
### App name
N26
### Package name
de.number26.android
### Link to app
https://play.google.com/store/apps/details?id=de.number26.android
### App version
4.39
### Version code
202547000
### Minimum SDK
API 28
### Target SDK
API 35
### Country of the app
DE
### Build Number
[2025112101](https://grapheneos.org/releases#changelog)
Latest Stable at time of creating this comment.
### Device
- [X] Pixel 8
### Receive security preview releases
- [X] Enabled
- [ ] Disabled
### Google Play installed
- [X] Installed
- [ ] Not installed
### Where did you install this app from?
- [ ] Google Play Store
- [X] Aurora Store
- [ ] Accrescent
- [ ] F-Droid Repository
- [ ] Other
### Google Play services Network permission revoked?
- [ ] Revoked
- [X] Not revoked
- [ ] Not installed
### SafetyNet Enforcement
- [ ] Enforced
- [ ] Not enforced
- [X] Unknown
### Play Integrity
- [X] Enforced
- [ ] Not enforced
- [ ] Unknown
### Secure app spawning
- [X] Enabled
- [ ] Disabled
### Exploit protection compatibility mode
- [X] Enabled (Tested)
- [X] Disabled
### Memory tagging (MTE)
- [X] Enabled
- [X] Disabled (Exploit protection compatibility mode)
### Hardened memory allocator
- [X] Enabled
- [X] Disabled (Exploit protection compatibility mode)
### Extended virtual address space
- [X] Enabled (Required by hardened_malloc)
- [ ] Enabled
- [X] Disabled (Exploit protection compatibility mode)
### Native code debugging
- [X] Enabled (Tested)
- [X] Disabled
### WebView JIT
- [X] Disabled
- [X] Enabled (Tested)
- [X] Enabled (de-facto enabled prior to GrapheneOS adding this toggle)
### Dynamic code loading via memory
- [X] Allowed
- [X] Allowed (de-facto enabled prior to GrapheneOS adding this toggle)
- [X] Restricted
### Dynamic code loading via storage
- [X] Allowed
- [X] Allowed (de-facto enabled prior to GrapheneOS adding this toggle)
- [X] Restricted
### Stock OS compatibility
- [ ] Works
- [ ] Does not work
- [X] Untested
### NFC payments
- [ ] Works
- [ ] Works - but requires another service
- [ ] Does not work
- [ ] Not supported
- [X] Not tested
### App permissions
- [X] Network
- [ ] Camera - Allow only while using the app
- [ ] Camera - Ask every time
- [ ] Notifications
- [ ] Sensors
### Profile app tested in
- [X] Owner profile
- [ ] Secondary profile(s)
- [ ] Private Space
- [ ] Other
### Description of the app's functionality
During the transition phase toward PIA, the app started behaving worse, with occasional errors, increasing over time, for example at random moments viewing a specific transaction, attempt to create a virtual card (And many others which I cannot name due to there being no clear pattern to me) generating an error, in which you could only refresh, but the app would fail to do so, and required you to close the app (swipe away from task bar) and re open it, and the login process (both with fingerprint and password) has become much more sluggish ever since adopting Play Integrity API.

### Are there any extra notes you think users should know about?

I attempted to block PIA from the first notification, and tried to diagnose whether other options, such as native code debugging and MTE would reduce the amount of issues, but unfortunately, only upon following the comment of @stephane-21 and allowing PIA, did the errors stop.

I cannot reproduce the issues that @Gakmots has, but we can potentially surmise that the added restrictions are worse for people who are not yet N26 customer, and that stricter checks are employed, as opposed to those who have been a customer prior to the bank utilizing PIA.

Should I have left out any details, or if you have any questions, please let me know and tag me.

Unfortunately due to the randomized pattern of the errors I cannot describe them well (inherent weakness of these type of problems, I am better at reporting when error logs are generated with clear details, whereas this is all quite vague), only that PIA allowed/blocked has a clear distinction.

### ADB logcat of the app if necessary
N/A

**Comment by mika** [comment]
> Currently I test it with N26 Version 4.36 from Sandboxed Play Store, Maybe it only require Strong Integrity at first login/register.. I can let it run without crash, but login/register/association is unavailable. Did you adjust any compatibility options?

I can confirm that creating a new N26 account with latest N26 version 4.41 from Sandboxed Play Store is *not* supported by GOS due to N26's Play Integrity API usage (see https://github.com/PrivSec-dev/banking-apps-compat-report/issues/342). Usage with an existing N26 account works so far though.

**Comment by HermesBote** [comment]
Thats so annoying! Unfortunally confriming Mikas experience above. Wondering, if there is a way to create a new bank account without this App and make it run this way?

**Comment by mika** [comment]
FTR, I managed to create an N26 account with an old + outdated (kind of insecure) Pixel 4a device. Waited for a few days to not run into fraud detection or alike, and then migrated the account to GOS. Annoying and cumbersome :-/ - but at least worked.

**Comment by spring-onion** [comment]
This is not good, please reach out to them and explain what's going on. #342 has a template you can use, you will want to edit it somewhat.

**Comment by Jecko-o** [comment]
> FTR, I managed to create an N26 account with an old + outdated (kind of insecure) Pixel 4a device. Waited for a few days to not run into fraud detection or alike, and then migrated the account to GOS. Annoying and cumbersome :-/ - but at least worked.

Hello @mika , I hope not to bother, could you tell me which steps you followed to migrate the account on a fresh GOS?
Thank you in advance anyway.

I already have an account working on my previous phone, but at the first attempts to pair on GOS I got stuck at the location section.
So I tried tinkering with the configuration, and after another try it seems like my device is now locked out.
Every time i try the process fail right after the login and trying to start it (with a message telling me to contact support for security reasons, with the drawing of a cat in the background).

I already tried that but it was very generic support. I'll try again when I have some spare time. But I don't think they will bother, especially when I tell them I am not on stock.

+1 on Gakmots  [comment](https://github.com/PrivSec-dev/banking-apps-compat-report/issues/21#issuecomment-3396398921), N26 should be put out of the list.
I was aware of the risk, but I was really looking forward to it working when I took the steps to try GOS.

**Comment by mika** [comment]
@Jecko-o nothing special on my side, really just started the n26 app on GOS (app permissions Network + Sensors) and followed https://support.n26.com/en-de/security/account-protection/how-to-connect-or-disconnect-my-smartphone-to-my-account to migrate from the other smartphone, sorry.

FTR, I also reached out to N26 support as suggested by @spring-onion, and informed them about the current state  and problems, and reported my wish to support GOS for creating new accounts, and also to keep it working with GOS as-is, hope further folks also follow.

**Comment by Jecko-o** [comment]
@mika thank you very much for replying.
I will try to reset play services and google play  storage and see if I can pass again the integrity check or not. And I will reach out the assistance about supporting GOS, for what is worth.
I am based in EU and I think it should be worth reaching our regulators too about the reliance of bank as well of state apps on play services in general.
But I really think really it should be the same of an issue in the US.
I can manage keeping the N26 app on the old phone anyways, or change bank, but I am really looking forward for a change that I think well due in the mobile ecosystem.

**Comment by leinad75** [comment]
I migrated my N26 from my old Android device to Graphene OS (with sandboxed Play Services installed) without problems. There was no issue regarding location (I have the default settings afaik).
Nevertheless, when I tried to change my e-mail address, it said that this is not possible and I should reach out to their support chat. Continuing, I was faced with a screen asking me to update to the latest version. But I am at the latest version (4.43 from 2026-01-27) of the Play Store.

**Comment by ao57772** [comment]
I had an issue today, the app wanted to perform face verifiation but it failed to open the camera, then reported a generic error. All access rights were ok. It worked sometimes november-december 2025 - I did not change anything except I had automatic updates on. I gave up fearing they will lock my account after many failed login attempts.

**Comment by Sedlinho** [comment]
I cannot get it working, tried to enable Location all the time for Google Play and services. My login screen just refreshes after I insert my username and password and shows empty login screen again. Any tips ideas how to resolve that?

**Comment by Genda1ph** [comment]
"For now" has stopped working: existing clients are required to scan their face, then it tries to verify device integrity and fails with a generic error.

After a few tries, the bank can request a password change via email, and then the app tells you it won't work on this device.

**Comment by WateryDuck** [comment]
This is the first time I'm posting on Github and in this GOS project, please forgive me if formatting is not ideal. I just want to contribute.

I have a different experience compared to users posting as of recent. I used the advice of @mika and @Nick1296 in this thread and succesfully migrated today **an already existing N26 account** from a stock android to GOS. Here are the details in case it can help someone:

**App version**
4.52

**Version code**
202623000

**Minimum SDK**
API 28

**Target SDK**
API 35

**Device**
Pixel 9 Pro

**Play Services installed?**
Yes, Sandboxed Play Services installed

**Permissions given to Play Services?** 
Network + Location

**App permissions**
Network + Sensors

**Where did you install this app from?**
Google Play Store

**App tested in**
Secondary profile

**Description of the app's functionality**
From the get go, the app tried to access sensors and I got a notification that the Play Integrity API was used. After inserting my username and password, I expected to be directed to the "Pair new device" flow as described by @mika. Instead however, I got prompted to take a selfie to verify that I am the legitimate owner of the account. Before clicking on "Continue" to start, I made sure to toggle the camera access to avoid breaking the flow and perhaps raising risk flags for the app. Once the selfie was taken, I was immediately approved and logged in to my account.

**Are there any extra notes you think users should know about?**
Three things that might have been crucial in my success:
1. I followed @Nick1296 's advice and made sure that I had the "Reroute location requests to the OS" toggled OFF under _settings -> apps -> sandboxed google play_ +
 enabled google location accuracy. I disabled that after the succesful migration.
2. I had this selfie security feature enabled for "new devices" or "suspicious payments" _before_ I started the migration to GOS.
3. I have observed a theme in user comments that lead me to believe to have the highest guarantees of success, banking apps need Network + Sensors permissions granted. This is what I applied here.

My experience therefore differs from comments from @Jecko-o , @ao57772 , @Sedlinho , and @Genda1ph for N26 compatibility in 2026. Please let me know if I can help out

**Comment by alexandroszacharakis8** [comment]
Just a short update. I seamlessly managed to log in to my existing account. I installed the app from Aurora and have play services enabled but without logging in to google play or giving network permissions to play store.

As suggested by @WateryDuck I had Sensors, Network and Camera (while using the app) permissions enabled. I did not need to reroute location to google and I had exploit protection compatibility toggled *off*. Just put credentials, was asked to take a selfie and I was just in!

Everything seems to be working fine for now (did a couple test transactions) including biometrics.

**Comment by waluwaz** [comment]
Good for those that were successful. But
On my Google-less user/profile, the app says "We can't create your account on this device. ..."
In my Google profile, Google Play fails to install the N26 app.

The N26 website lists as requirement
"Native support of Google Services"
https://support.n26.com/en-fr/app-and-features/app/can-i-download-the-n26-app-on-my-smartphone
And their chatbot will add:
"Some manufacturers don't have rights to use Android and Google services. Even if their operating system is based on Android (like Amazon Fire, Oxygen OS), they may not be compatible with N26. Always verify with the manufacturer."

Regardless of whether their statements are technically correct, it seems clear that their strategy is to not bother and simply rely on/require Google.

**Comment by pimeys** [comment]
I called them as a metal customer with some savings etc. with them. My dedicated customer support agent said to me that they will not block Graphene OS customers now or in the future. But there's a little trick for people that just test Graphene OS in a secondary device: you have to have a SIM card installed to the phone before installing the app and logging in. They will always ask to take a selfie, but if the phone has no SIM card it will just say that the face recognition failed.

But yes yes, I'm an existing customer. I don't know how it is for new customers...

Edit: another common issue, if you're logged in two phones at the same time, the other one when asking the photo will just fail until you've turned off the other phone. Remember this when testing a new GrapheneOS device.
