### ISSUE TITLE
Natwest

### ISSUE THREAD

**Issue by hjangadi** [akc3n/banking#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Natwest

### Link to app

Play Store

### App version

07.14.0000.20.0

### Country of the app

United Kingdom

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Hi All,

This works absolutely fine on Pixel 6 running with Sandbox google services with GrapheneOS; happy to use grapheneOS until I get support. No going back to Pixel stock. 

As my NFC payment system also resolved with Stocard app. I recommend this.

### Are there any extra notes you think users should know about?

As my NFC payment system also resolved with Stocard app as Gpay didnt work on my GrapheneOS althought I have installed Sanbox Google services. I recommend this.

### ADB logcat of the app if necessary

no, not required.

**Comment by akc3n** [comment]
@hjangadi Thank you for your submitted report

Would you please be able to confirm which NatWest mobile backing app it is?
https://play.google.com/store/search?q=Natwest&c=apps&hl=en

- [ ] Verify with @hjangadi which specific NatWest mobile banking app they are referring to for `Link to App` section

**Comment by hjangadi** [comment]
Sorry again app full name is: Natwest Mobile Banking UK
https://play.google.com/store/apps/details?id=com.rbs.mobile.android.natwest&hl=en

**Comment by akc3n** [comment]
Thank you @hjangadi

**Comment by tommytran732** [comment]
The app stopped working recently. I am going to remove it. Please open a new report should something change.

**Comment by Metr0pl3x** [comment]
Curious how it stopped working, been using the app since Play Service integration without issue Pixel 4a and 6a.

Link to my report prior to finding this:

https://github.com/PrivSec-dev/banking-apps-compat-report/issues/234

Fully working.

**Comment by the-red-lily** [comment]
Note that stocard no longer supports NFC credit or debit card payments

**Comment by howroyd** [comment]
Stocard is now closed down. Is anyone able to run this test again, please?

**Comment by null-von-sushi** [comment]
I never used Stocard, but since the main topic is NatWest, I also wanna say NatWest seems to still continue to work for me. One of the main reasons I keep it around tbh.

(If Stocard was just a workaround for Google Pay not working then consider Curve (Google Play version even, any guides specifying Huawei AppGallery version are outdated)).

**Comment by Henry112** [comment]
App works great!
Pixel 9a

**Comment by d34ndev** [comment]
An update for July 2026. Just tried to launch the app - v07.67.0000.31083.0 what a version number... - sometimes it loads and asks for the login details but more often it says I'm on an "unsupported device" because it says "This app requires Google Mobile services in order to function".

After installing the sandboxed Google Play Services it appears to load fine.

Having done an online chat with them saying this, they responded with "I appreciate your feedback regarding GrapheneOS compatibility. While we're unable to provide a workaround, I can certainly suggest that you submit this as feedback for consideration by our Digital Banking team.

In the meantime, you can continue to access your accounts through Online Banking using a supported web browser."

I've also sent feedback to their team and will update if I hear back from them.

**Comment by Metr0pl3x** [comment]
> An update for July 2026. Just tried to launch the app - v07.67.0000.31083.0 what a version number... - sometimes it loads and asks for the login details but more often it says I'm on an "unsupported device" because it says "This app requires Google Mobile services in order to function".
> 
> After installing the sandboxed Google Play Services it appears to load fine.
> 
> Having done an online chat with them saying this, they responded with "I appreciate your feedback regarding GrapheneOS compatibility. While we're unable to provide a workaround, I can certainly suggest that you submit this as feedback for consideration by our Digital Banking team.
> 
> In the meantime, you can continue to access your accounts through Online Banking using a supported web browser."
> 
> I've also sent feedback to their team and will update if I hear back from them.

Thanks for this, I can confirm this continues to function so long as Play Services is present without issue.
