### ISSUE TITLE
[NL] Rabobank

### ISSUE THREAD

**Issue by Shizmob** [akc3n/banking#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Rabobank

### Link to app

https://play.google.com/store/apps/details?id=nl.rabomobiel

### App version

7.16.0

### Country of the app

Netherlands

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Used the regular, Rabo Scanner-based, sign-up flow. Worked just like on the phone's vendor OS.

**Comment by akc3n** [comment]
@Shizmob Thank you!

**Comment by Mikey0175** [comment]
After 19th of july 2025 the app can't be installed anymore from playstore on latest GrapheneOS on pixel 9.

When you have the app already installed, it works, but for how long?

**Comment by spring-onion** [comment]
@ph00lt0 Apparently it continues to work (for now) if installed through the aurora store. See the duplicate report.

**Comment by ismael86** [comment]
It does work through the aurora store and even activates using the face scanner (when activated using the face scanner and ID you don't have to use the rabo scanner anymore even with larger payments).
I did have to activate exploit protection compatibility mode otherwise it wouldn't launch.

Tested with the pixel 10 and pixel 10 pro.

**Comment by mklinik** [comment]
I know that this issue is for GrapheneOS, but I just wanted to report that I sucessfully got the Rabobank App working on LineageOS. I installed the Aurora App Store from F-Droid, and then installed the Rabobank App from Aurora. It works. Samsung Galaxy S10, LineageOS 23.2

**Comment by jja2000** [comment]
Got locked out of the app today on an unupdated version. They seem to be more strict on app versions now.

**Comment by jrbergen** [comment]
Rabobank app no longer supports GrapheneOS. Time to move to a different bank.

**Comment by Juerd** [comment]
Older version stopped working today, app no longer installable from Play Store.

Eventually managed to install an update (7.55.3) using Aurora Store, but will probably change banks soon because Rabobank can apparently no longer be relied on.

**Comment by Kewner** [comment]
@Juerd same here, an update through Aurora Store fixed it for me. You mentioned changing banks anyway because Rabobank can no longer be relied on - would you mind elaborating on that? If it works, it works, right? There might be something I'm not fully understanding though, as I probably have some reading to do on the whole Play Integrity API stuff.

**Comment by damige** [comment]
Called the bank today to complain. They stated they have received multiple calls on this issue today. 
Please call your bank to report you are affected by this issue also.

> [@Juerd](https://github.com/Juerd) same here, an update through Aurora Store fixed it for me. You mentioned changing banks anyway because Rabobank can no longer be relied on - would you mind elaborating on that? If it works, it works, right? There might be something I'm not fully understanding though, as I probably have some reading to do on the whole Play Integrity API stuff.

Sideloading through aurora store works, but:
[tweakers](https://tweakers.net/nieuws/238036/rabobank-app-werkt-niet-meer-op-alternatieve-android-roms-vanwege-integrity-api.html) states that the app will require Google-Play Integrity-checks. This often includes the source of where the app was installed from (and including apk hash, signing keys, rooted device check etc). This means that if they decide to enforce the integrity check completely, sideloading will also no longer be possible.

In my mind blocking grapheneos from installing through the playstore is merely step one of Google-Play Integrity compliance.

**Comment by MrD0r1n** [comment]
Filled in a report (because suggested by @damige ) and got called back. In summary: they understand the situation is unpleasant, but they won't make an exception for GrapheneOS. 

Still available via Aurora (for now). Otherwise, best bet is to use the browser instead, use a separate phone or switch banks. I hear good things about Triodos Bank.

**Comment by DeanLemans** [comment]
I will also call later today

**Comment by Juerd** [comment]
Have called Rabobank business support. I explained that I could no longer find the Rabobank app in the Play Store, and that I feared that they would have indeed blocked custom roms including GrapheneOS. The customer support agent knew what GrapheneOS was, and couldn't imagine that they would actually block an up-to-date version of an operating system known for its high security, and that if this were the case, it must surely have been by mistake.

We've checked that the app can be found via a direct link (but can't be installed that way, and there's a message that the app is no longer available for this device), and the agent has tried to find internal information regarding this issue, to no avail.

To be continued... (phone appointment scheduled for tomorrow).

**Comment by proairface** [comment]
I have contacted the Rabobank about this issue as well but as a consumer you are basically powerless. I received generic emails from their support to check my Android version, if there are updates, and to see if my device passes the integrity checks. I managed to update the app through the Aurora store but I am looking at other banks. The blind, unwavering loyalty to Google and the Pax Americana is just ridiculous. Thanks for the comments and tips gentlemen, much appreciated. Working again now on my Google Pixel 9 Pro XL with GrapheneOS

**Comment by DeanLemans** [comment]
shouldnt this be opened again then?

**Comment by spring-onion** [comment]
> shouldnt this be opened again then?

The way forward is for everyone here to keep bringing up the problem to them so they take it seriously. What could also prove to be effective for them to at least reconsider their decision is if you warn them they will lose you as a customer if they don't fix it (and of course going through with it if it comes to that). It's good that you can at least continue to use it through the aurora store but full breakage is just a step or two away now.

**Comment by JvanderStad** [comment]
For anyone affected by this, I would encourage you to file a formal complaint with Rabobank as well. The more customers report this issue, the more likely it is to receive attention.

Complaint form:
https://www.rabobank.nl/bedrijven/feedback/klacht/formulier

Below are the texts I used. Feel free to adapt them to your own situation.

**Complaint (Dutch):**

> Als softwareontwikkelaar en security researcher reis ik veel en neem ik de beveiliging van mijn digitale omgeving uiterst serieus. Daarom gebruik ik GrapheneOS: een beveiligde, Android-compatibele distributie die wereldwijd door securityprofessionals wordt gebruikt. Tot mijn teleurstelling blokkeert de Rabobank-app dit platform zonder aantoonbare technische noodzaak. Ik verwacht dat ik mijn bankzaken veilig én praktisch kan uitvoeren. Door GrapheneOS uit te sluiten dwingt Rabobank mij feitelijk een minder privacyvriendelijk platform te gebruiken of een andere bank te overwegen.

**Requested solution (Dutch):**

> Herzie het detectiebeleid en ondersteun GrapheneOS, of maak gebruik van objectieve integriteitscontroles zoals hardware-attestatie in plaats van het besturingssysteem te blokkeren. Ik wil mijn bankzaken veilig kunnen uitvoeren zonder mijn privacy of beveiligingskeuzes te hoeven opgeven.

If you submit a complaint, it may also help to mention:

* that GrapheneOS is Android-compatible and not rooted by default;
* that many security professionals use it specifically because of its security hardening;
* that banking apps should rely on objective device integrity and attestation rather than blocking an entire Android distribution.

Hopefully, if enough customers provide constructive feedback, Rabobank will reconsider its current policy.

**Comment by BalkanMadman** [comment]
Interestingly, the Aurora Store version works (as of v8.0.2), apart from banking without Rabo Scanner. Face recognition just fails over and over. 

I don't know whether it's related to GrapheneOS or just a coincidence. Does anybody else have this issue?

(Face recognition is what you use when first logging in Rabo app when (re)installing it).

**Comment by DeanLemans** [comment]
Face recognition also failed for me

**Comment by BalkanMadman** [comment]
the Deep State doesn't want you to use Rabobank without Rabo Scanner on GrapheneOS
