### ISSUE TITLE
MobilePay - Denmark

### ISSUE THREAD

**Issue by oumno** [akc3n/banking#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

MobilePay

### Link to app

https://play.google.com/store/apps/details?id=dk.danskebank.mobilepay

### App version

5.13.0

### Device

- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [x] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

This app works. You can send money, receive money, see the history of transactions. You can enable biometrics and access the app's settings.

### Are there any extra notes you think users should know about?

This is MobilePay for Denmark.

The app works without Google Play, but it will show a warning everytime you open the app. Notifications don't work when not having Google Play installed.

**Comment by akc3n** [comment]
@oumno Thank you!

**Comment by fortXIV** [comment]
Currently it doesnt work for me - and I think it has something to do with vanadium. I had all the same settings, but it seems like MitID cant recognize that the request has been accepted, which it why it gives an error. Every other app that wasnt running vanadium webview, such as: jyskebank, nordea, MitID app, kørekort etc. worked fine since they werent using vanadium, but mobile is the only one which wasnt working.

**Comment by eennoo** [comment]
I cannot test MobilePay as I reside in a different contry and they don't allow foreign numbers for some unknown reason...

The other apps you talk about, when you say they weren't running Vanadium Webview, did they just run something natively in their apps? I don't think one can change the webview that is used in GrapheneOS. 

A longshot: But could you enable Javascript JIT for the site under its site settings in Vanadium Settings -> Site Settings -> All sites -> Find either mobilepay och mitid (whatever URL they use for this sign-in page) and enable JIT. Like I said, maybe it's not solving it, but could be worth a try.

**Comment by fortXIV** [comment]
> I cannot test MobilePay as I reside in a different contry and they don't allow foreign numbers for some unknown reason...
> 
> The other apps you talk about, when you say they weren't running Vanadium Webview, did they just run something natively in their apps? I don't think one can change the webview that is used in GrapheneOS.
> 
> A longshot: But could you enable Javascript JIT for the site under its site settings in Vanadium Settings -> Site Settings -> All sites -> Find either mobilepay och mitid (whatever URL they use for this sign-in page) and enable JIT. Like I said, maybe it's not solving it, but could be worth a try.

The app only allows signup from danish numbers since its an app for danes. The other apps would open a custom tabs (i think its called that atleast?) in brave, which would work fine. Btw I did have JIT, javascript and third party cookies enabled for the site(s), nothing would work. The only solution i found was the one outlined above. In that version (and probably versions before that) it would actually open in the browser you specified as your standard webbrowser, not just vanadium which wouldnt work at all.

**Comment by fortXIV** [comment]
Updating the app afterwards hasnt caused issues (at least not so far, but maybe could when purchasing goods online i think).

**Comment by eennoo** [comment]
Yes. I know it cannot be registered on foreign numbers. I do have a Danish account + MitID so it was just a comment on MobilePay's (made-up) limitations and I was the one who submitted the initial report. 

So when Jyske etc opens MitID's authentication page, it opens in it in a browser, whereas MobilePay just opens it in the actual app (in a webview as you suspect). Does MitID work alright for you - as I suspect MitID is the app to blame here (as it always is). I just tried to login on Skat.dk with Vanadium. I got an error occured after approving the login in MitID and navigating back to Vanadium. When I tried it in Firefox (Nightly), it worked.

So is the MitID login flow working for you at all in Vanadium?

**Comment by fortXIV** [comment]
> Yes. I know it cannot be registered on foreign numbers. I do have a Danish account + MitID so it was just a comment on MobilePay's (made-up) limitations and I was the one who submitted the initial report.
> 
> So when Jyske etc opens MitID's authentication page, it opens it in a browser, whereas MobilePay just opens it in the actual app (in a webview, as you suspect). Does MitID work alright for you - as I suspect MitID is the app to blame here (as it always is). I just tried to login on Skat.dk with Vanadium. I got an error occured after approving the login in MitID and navigating back to Vanadium. When I tried it in Firefox (Nightly), it worked.
> 
> So is the MitID login flow working for you at all in Vanadium?

MitID and other apps that require MitID works perfectly fine if you dont use Vanadium, which is why I think Vanadium is to blame here. The 7 other apps where I logged in with MitID, they opened in brave browser, so everything worked flawlessly. However, MobilePay after version 5.26+ would just force me to use Vanadium no matter what I did, which is why I suspected that Vanadium was the reason why I couldn't login to MobilePay.

https://github.com/GrapheneOS/Vanadium/issues/421 <--- that's why I also made this report on Vanadiums' GH. Thankfully I found the workaround but it would still be nice to have this fixed since it could very well affect other apps since the same people that makes MitID, also made similar governmental authentication apps for swedish, dutch, belgian, finnish and norwegian citizens (https://www.criipto.com/ - scroll down to "supported eIDs")

**Comment by eennoo** [comment]
Good that you filed an issue for Vanadium. Probably where this issue will be solvedd. 

Ah, I do think MitID is it own kind of special (the launch still gives me nightmares...). The BankID (in Sweden) would never have a webview for log in as the app/website will redirect you to the BankID app immedatiely. It works way differently from the MitID one. It doesn't have a weak step where you put in a username, like the MitID app has. 

But thanks for reporting to the Vanadium repo.

**Comment by StefanHoegh** [comment]
> > Yes. I know it cannot be registered on foreign numbers. I do have a Danish account + MitID so it was just a comment on MobilePay's (made-up) limitations and I was the one who submitted the initial report.
> > So when Jyske etc opens MitID's authentication page, it opens it in a browser, whereas MobilePay just opens it in the actual app (in a webview, as you suspect). Does MitID work alright for you - as I suspect MitID is the app to blame here (as it always is). I just tried to login on Skat.dk with Vanadium. I got an error occured after approving the login in MitID and navigating back to Vanadium. When I tried it in Firefox (Nightly), it worked.
> > So is the MitID login flow working for you at all in Vanadium?
> 
> MitID and other apps that require MitID works perfectly fine if you dont use Vanadium, which is why I think Vanadium is to blame here. The 7 other apps where I logged in with MitID, they opened in brave browser, so everything worked flawlessly. However, MobilePay after version 5.26+ would just force me to use Vanadium no matter what I did, which is why I suspected that Vanadium was the reason why I couldn't login to MobilePay.
> 
> [GrapheneOS/Vanadium#421](https://github.com/GrapheneOS/Vanadium/issues/421) <--- that's why I also made this report on Vanadiums' GH. Thankfully I found the workaround but it would still be nice to have this fixed since it could very well affect other apps since the same company that made MitID, also made similar governmental authentication apps for swedish, dutch, belgian, finnish and norwegian citizens (https://www.criipto.com/ - scroll down to "supported eIDs")

Does your MobilePay still work and if so, what version are you using?
It's the only thing keeping me from trying to install GrapheneOS on my phone again.
