### ISSUE TITLE
CommBank - Australia (submitting for non-gh user)

### ISSUE THREAD

**Issue by akc3n** [akc3n/banking#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

CommBank

### Link to app

https://play.google.com/store/apps/details?id=com.commbank.netbank

### App version

4.29.0.2113

### Country of the app

Australia

### Build Number

SP2A.220405.003.2022041600

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [X] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [X] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

> "CommBank" will open successfully in an owner profile without any of the google compatibility layer stuff and all functionality works, except the inbuilt tap and pay feature that is ingrained in Android settings under "contactless payment". On a second user profile with the google compatibility layer installed and network permissions granted to all google stuff, the tap and pay feature does work.

Quoted from DM message from user whom submitted this app report me via matrix.

### Are there any extra notes you think users should know about?

> i think CommBank checks something about SafetyNet when using tap and pay because when I used LineageOS with microG, tap and pay did not work.

> Quoted from DM message from user whom submitted this app report to me via matrix.

### ADB logcat of the app if necessary

n/a

**Comment by Z0pyrus** [comment]
Today I tried to login using my fingerprint, but it won't let me because it says "your device is rooted" (it's not).
Can someone else also confirm this happening on another device?

(Google Pixel 6, Android 14, GrapheneOS 2024031400)

**Comment by stags38charter** [comment]
Update:

App version: Version 5.39.0.2510

Build Number: 2025102601

Device: Pixel 7

Profile app tested in: Owner and Private Space

Google Play installed?: Works with and without Play Services although push notifications, NFC payments and the location feature relying on Google Maps do not work without Play Services installed.

Where did you install this app from?: Play Store and Aurora Store

Native code debugging: Blocked

Exploit protection compatibility mode: Disabled

Memory tagging: Disabled (I do not have a Pixel 8 or above).

Dynamic code loading via memory: Restricted

Dynamic code loading via storage: Restricted

Does the app use the Play Integrity API?: Yeah, I do not block it as it doesn’t cause problems. Play Integrity API is used whenever the app is launched.

NFC payments: Works but requires Play Services.

**Comment by Alastair-L** [comment]
I hope it is helpful to provide an update since the app got a significant update. It seems to still work although I haven't tried NFC payments. Also, the information below is just what I have set, not necessarily the minimum/best required.



App version: Version 5.48.1.2576

Build Number: ?

Device: Pixel 8a

Profile app tested in: ?

Google Play installed?: Play services are installed

Where did you install this app from?: Aurora Store

Native code debugging: Allowed

Exploit protection compatibility mode: Disabled

Memory tagging: Disabled.

Dynamic code loading via memory: Allowed

Dynamic code loading via storage: Allowed

Does the app use the Play Integrity API?: Yeah, I do not block it as it doesn’t cause problems. Play Integrity API is used whenever the app is launched. Same.

NFC payments: Not sure. Haven't tested.
